microphone:
  channels: 1
  samplerate: 16000
  chunk: 4000
  device_index: 7
  dtype: int16
  engine_type: sounddevice
  sounddevice:
    stream_type: numpy

chatbot:
  channels: 1
  samplerate: 16000
  chunk: 4000
  language_code: id
  engine_type: dialogflow
  dialogflow:
    project_id: robosemarhealth-jxgh
    application_credentials: E:\Sanditheta Solusi Digital\suarasemar\credentials\robosemarhealth-jxgh-8a8b99fefe05.json
  